### ISSUE TITLE
Universal selector can't follow a comment

### ISSUE THREAD

**Issue by damsfx** [assetic-php/assetic#31]
When css file contains an universel selector following a comment, with another comment far in file or comment in var, it is then considered as a opening comment .   

**With comment in var**
In: 
```css
/*! Keep me */*{box-sizing: border-box;}.form{--ring-inset: var(--empty, /*!*/ /*!*/);border: 0;}
```
Expected:
```css
/*! Keep me */*{box-sizing:border-box}.form{--ring-inset:var(--empty,/*!*/ /*!*/);border:0}
```
Output: 
```css
/*! Keep me * /*!*/);border:0}
```

**With another comment**
In: 
```css
/*! Keep me */*{box-sizing: border-box;}/* Remove me */.noborder{border: 0;}
```
Expected:
```css
/*! Keep me */*{box-sizing:border-box}.noborder{border:0}
```
Output: 
```css
/*! Keep me *.noborder{border:0}
```

I encountered this bug when using Laravel Mix with TailwindCss.  
In Mix `cssNano.discardComments` is true by default, so the css code is compacted, and the universal selector is then appended to the Tailwind retained comment: 
```css
@charset "UTF-8";
/*! tailwindcss v3.0.23 | MIT License | https://tailwindcss.com*/*,:after,:before{border:0 solid #e7e5e4;box-sizing:border-box} ...
```
