### ISSUE TITLE
Example for symfony 5 or 6 integration?

### ISSUE THREAD

**Issue by rofthedeep** [assetic-php/assetic#34]
Hi!

First, thx for your great work!

At the moment I'm trying to get the package connected to my symfony 5 project. But i'm too stupid to get the twig integration running.
Do you know a working example for this where I can have a look at?
Best,
Tim

**Comment by LukeTowers** [comment]
Not sure tbh, we use it with @wintercms and we don't use the Twig integration. What sort of issues have you run into so far?

**Comment by cklm** [comment]
Following config works for me (symfony 5.4):

```yaml
    # services.yaml
    
    app.assetic.factory:
        class: Assetic\Factory\AssetFactory
        arguments:
            - '%kernel.project_dir%/public/assets'
            - '%kernel.debug%'
    
    Assetic\Extension\Twig\AsseticExtension:
        arguments:
            - '@app.assetic.factory'
        tags:
            - 'twig.extension'
```

Then use twig-tags as documented. Whats missing is a command similar to `assetic:dump` in sf 3.4, which dumps the files once at deployment.
